//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerService
    {
        public int idCustomerService { get; set; }
        public Nullable<int> fkidCustomer { get; set; }
        public Nullable<int> fkidService { get; set; }
        public Nullable<int> sessionsNumber { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Service Service { get; set; }
    }
}
