//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessProjectEntities : DbContext
    {
        public BusinessProjectEntities()
            : base("name=BusinessProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customerService> customerServices { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<modulo> moduloes { get; set; }
        public virtual DbSet<operacione> operaciones { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<ProviderService> ProviderServices { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<SalesMan> SalesMen { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceSalesman> ServiceSalesmen { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<typeProvider> typeProviders { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
