//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.ProviderServices = new HashSet<ProviderService>();
        }
    
        public int idProvider { get; set; }
        public string nameProvider { get; set; }
        public string addressProvider { get; set; }
        public string emailAddressProvider { get; set; }
        public Nullable<int> phoneProvider { get; set; }
        public string descriptionProvider { get; set; }
        public Nullable<int> fkTypeProvider { get; set; }
    
        public virtual typeProvider typeProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderService> ProviderServices { get; set; }
    }
}
