//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderService
    {
        public int idProviderService { get; set; }
        public Nullable<int> fkIdProvider { get; set; }
        public Nullable<int> fkIdService { get; set; }
    
        public virtual provider provider { get; set; }
        public virtual Service Service { get; set; }
    }
}
