//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesMan()
        {
            this.ServiceSalesmen = new HashSet<ServiceSalesman>();
        }
    
        public int idSalesMan { get; set; }
        public string nameSalesman { get; set; }
        public string addressSalesMan { get; set; }
        public string emailAddressSalesMan { get; set; }
        public Nullable<int> phoneProvider { get; set; }
        public Nullable<double> salarySalesMan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceSalesman> ServiceSalesmen { get; set; }
    }
}
