//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.customerServices = new HashSet<customerService>();
            this.ProviderServices = new HashSet<ProviderService>();
            this.ServiceSalesmen = new HashSet<ServiceSalesman>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int idService { get; set; }
        public string nameService { get; set; }
        public string descriptionService { get; set; }
        public Nullable<System.DateTime> startDateService { get; set; }
        public Nullable<System.DateTime> endDateService { get; set; }
        public Nullable<double> valueService { get; set; }
        public Nullable<int> commissionPercentageBusinessService { get; set; }
        public Nullable<int> commissionPercentageSalesManService { get; set; }
        public string imageUrlServices { get; set; }
        public byte[] imageServices { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerService> customerServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderService> ProviderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceSalesman> ServiceSalesmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
