//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSalesman
    {
        public int idServiceSalesman { get; set; }
        public Nullable<int> fkidService { get; set; }
        public Nullable<int> fkIdSalesman { get; set; }
        public Nullable<int> totalCommissionServiceSalesman { get; set; }
    
        public virtual SalesMan SalesMan { get; set; }
        public virtual Service Service { get; set; }
    }
}
