//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int idSession { get; set; }
        public Nullable<System.DateTime> dateSession { get; set; }
        public Nullable<System.DateTime> startTimeSession { get; set; }
        public Nullable<int> durationSession { get; set; }
        public string statusSession { get; set; }
        public Nullable<int> fkIdEmployee { get; set; }
        public Nullable<int> fkIdCustomer { get; set; }
        public Nullable<int> fkIdService { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
